n1=input('enter your first num: ')
n2=input('enter your second num: ')
n1=float(n1)
n2=int(n2)
addition=(n1) + (n2)
subtraction=(n1) - (n2)
multiplication=(n1) * (n2)
division=(n1) / (n2)
print("result")
print('addition' ,addition)
print('subtraction' ,subtraction)
print('multiplication' ,multiplication)
print('division' ,division)